runs:

  using: "composite"

  steps:

  - name: Debug workflow
    shell: bash
    run: cmake --workflow --preset debug

  - name: Release workflow
    shell: bash
    run: cmake --workflow --preset release
