name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CTEST_NO_TESTS_ACTION: error
  CTEST_PARALLEL_LEVEL: 0

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.f90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  linux-new:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    strategy:
      matrix:
        gcc-version: [12, 13, 14]

    env:
      CC: gcc-${{ matrix.gcc-version }}
      CXX: g++-${{ matrix.gcc-version }}
      FC: gfortran-${{ matrix.gcc-version }}

    steps:
    - &checkout
      uses: actions/checkout@v5

    - uses: ./.github/workflows/composite-action


  linux-old:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    strategy:
      matrix:
        gcc-version: [9, 10, 11]

    env:
      CC: gcc-${{ matrix.gcc-version }}
      CXX: g++-${{ matrix.gcc-version }}
      FC: gfortran-${{ matrix.gcc-version }}

    steps:
    - *checkout

    - name: GCC APT
      if: matrix.gcc-version < 11
      run: |
        sudo apt update -y
        sudo apt install -y --no-install-recommends gcc-${{ matrix.gcc-version }} g++-${{ matrix.gcc-version }} gfortran-${{ matrix.gcc-version }}

    - uses: ./.github/workflows/composite-action


  linux-clang:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    strategy:
      matrix:
        clang-version: [16, 17, 18]

    env:
      CC: clang-${{ matrix.clang-version }}
      CXX: clang++-${{ matrix.clang-version }}

    steps:
    - *checkout
    - uses: ./.github/workflows/composite-action


  valgrind-memory:
    runs-on: ubuntu-24.04
    needs: linux-new
    timeout-minutes: 10

    steps:
    - name: install valgrind
      run: |
        sudo apt update
        sudo apt install --no-install-recommends valgrind

    - *checkout

    - run: ctest -S memcheck.cmake -V -LE python


  mac:
    runs-on: macos-latest
    timeout-minutes: 10

    strategy:
      matrix:
        compiler: [ {cpp: clang++, c: clang},
                    {cpp: g++-15, c: gcc-15} ]

    env:
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cpp }}
      FC: gfortran-15

    steps:
    - *checkout

    - uses: ./.github/workflows/composite-action


  windows:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: msys2/setup-msys2@v2
      id: msys2
      with:
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc-fortran

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ steps.msys2.outputs.msys2-location }}/ucrt64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - *checkout

    - name: Debug workflow
      run: cmake --workflow debug

    - name: Release workflow
      run: cmake --workflow release
