name: ci_msvc

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci_msvc.yml"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  msvc:
    runs-on: windows-2025
# used windows-2025 temporarily to skip ahead to latest ABI for GetFileInformationByName()
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v6

    - name: config
      run: cmake -Bbuild -Dfortran=no

    - name: Debug build
      run: cmake --build build --config Debug

    - name: Debug test
      run: ctest --test-dir build -C Debug -V

    - name: Debug print on fail
      if: failure()
      run: ctest --test-dir build -C Debug -V --rerun-failed

    - name: Release build
      run: cmake --build build --config Release

    - name: Release test
      run: ctest --test-dir build -C Release -V

    - name: Release print on fail
      if: failure()
      run: ctest --test-dir build -C Release -V --rerun-failed
